default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: freedomboard_development
  username: app
  password: password1

test:
  <<: *default
  database: freedomboard_test
  username: app
  password: password1

production:
  <<: *default
  database: freedomboard_production
  username: freedomboard
  password: <%= ENV['FREEDOMBOARD_DATABASE_PASSWORD'] %>